### ISSUE TITLE
It don't work

### ISSUE THREAD

**Issue by 0ceanManmn** [kingofnetflix/ultraviolet-actions#2]
I tried to reset the fork and the link still wont work

**Comment by Gray0112** [comment]
me too

**Comment by kingofnetflix** [comment]
contact me on discord, KingOfNetflix#7044 and we can get it situatied. Sorry about the late response

**Comment by kingofnetflix** [comment]
Did you follow it directly like I explained? Is it blocked, and just saying it's not working? giving this like a month until I close the issue
