### ISSUE TITLE
GOD DAMN

### ISSUE THREAD

**Issue by jbxskm** [kingofnetflix/ultraviolet-actions#6]
it doesnt support now.gg
fix the proxy
![image](https://user-images.githubusercontent.com/111071747/212967406-ce28d40e-f7ad-4a8a-8e5f-3c5067e67a56.png)

**Comment by kingofnetflix** [comment]
its because ultraviolet dosen't have a bypass for that, I can't fix it and you shouldn't go make a report in the Ultraviolet or Amythest Network's repo(s) either.
